# Generated by Django 3.2.12 on 2024-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_to_terms',
            field=models.BooleanField(default=False, verbose_name='Agree to Terms of Use'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Default Name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
