# Generated by Django 3.2.12 on 2024-02-19 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240219_1817'),
    ]

    operations = [
    ]
