# Generated by Django 3.2.12 on 2024-02-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240219_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_repeat',
            field=models.CharField(default='', max_length=255, verbose_name='Repeat Password'),
        ),
    ]
